export const commentConstants = {
  CREATE_REQUEST: "COMMENT_CREATE_REQUEST",
  CREATE_SUCCESS: "COMMENT_CREATE_SUCCESS",
  CREATE_FAILURE: "COMMENT_CREATE_FAILURE",

  GETALL_REQUEST: "COMMENT_GETALL_REQUEST",
  GETALL_SUCCESS: "COMMENT_GETALL_SUCCESS",
  GETALL_FAILURE: "COMMENT_GETALL_FAILURE",
};
