export const commentConstants = {
  CREATE_REQUEST: "COMMENT_CREATE_REQUEST",
  CREATE_SUCCESS: "COMMENT_CREATE_SUCCESS",
  CREATE_FAILURE: "COMMENT_CREATE_FAILURE",

  GETALL_REQUEST: "COMMENT_GETALL_REQUEST",
  GETALL_SUCCESS: "COMMENT_GETALL_SUCCESS",
  GETALL_FAILURE: "COMMENT_GETALL_FAILURE",

  DELETE_REQUEST: "COMMENT_DELETE_REQUEST",
  DELETE_SUCCESS: "COMMENT_DELETE_SUCCESS",
  DELETE_FAILURE: "COMMENT_DELETE_FAILURE",

  UPDATE_REQUEST: "COMMENT_UPDATE_REQUEST",
  UPDATE_SUCCESS: "COMMENT_UPDATE_SUCCESS",
  UPDATE_FAILURE: "COMMENT_UPDATE_FAILURE",
};
