export const organizationConstants = {
  GETALL_REQUEST: "ORGANIZATIONS_GETALL_REQUEST",
  GETALL_SUCCESS: "ORGANIZATIONS_GETALL_SUCCESS",
  GETALL_FAILURE: "ORGANIZATIONS_GETALL_FAILURE",

  CREATE_REQUEST: "ORGANIZATIONS_CREATE_REQUEST",
  CREATE_SUCCESS: "ORGANIZATIONS_CREATE_SUCCESS",
  CREATE_FAILURE: "ORGANIZATIONS_CREATE_FAILURE",

  GET_PAGE_COUNT: "GET_PAGE_COUNT",
};
