export const taskConstants = {
  CREATE_REQUEST: "TASK_CREATE_REQUEST",
  CREATE_SUCCESS: "TASK_CREATE_SUCCESS",
  CREATE_FAILURE: "TASK_CREATE_FAILURE",

  GETALL_REQUEST: "GETALL_REQUEST",
  GETALL_SUCCESS: "GETALL_SUCCESS",
  GETALL_FAILURE: "GETALL_FAILURE",

  GET_PAGE_COUNT: "GET_PAGE_COUNT",
};
